on:
  push:
    branches:
      - main
jobs:
  Check-out-the-code:
    runs-on: self-hosted
    steps:
      - name: actions/checkout@v4.1.2
        run: echo "Checkout finished :)"
      - name: Deploy the code
        run: |
          pwd
          cp -fR . /var/www/html/
          echo "Files were Copied successfully!"
