on:
  push:
    branches:
      - main
jobs:
  Check-out-the-code:
    runs-on: self-hosted
    steps:
      - name: actions/checkout@v4.1.2
        run: echo "Checkout finished :)"
      - name: Deploy the code
        run: |
          cd /var/www/html/site1
          git archive --format=tar --remote=https://${{ secrets.my_token }}@github.com/bashk/ci_cd_test.git master | tar -xf -
          # git init
          # git remote add origin https://${{ secrets.my_token }}@github.com/bashk/ci_cd_test.git
          # git fetch origin branchname:refs/remotes/origin/main
          # git checkout -b master --track origin/master
          # git reset origin/master
